WIP: refactoring

diff --git a/bin/bytes b/bin/bytes
--- a/bin/bytes
+++ b/bin/bytes
@@ -1,21 +1,27 @@
-#!/bin/bash
-#Sum the number of bytes in a directory listing
-VERSION=1.3.0
-TOTAL_BYTES=0
-UNIT=bytes
-DIR=.
-LS_OPTS=l
-PRINT_NEWLINE=true
-PRECISION=3
-NUMBER_REGEX="^[0-9]+$"
-UNIT_FACTOR=1
+#!/usr/bin/env bash
 
-function printUsageAndExit {
-  echo "Usage: bytes [-u | --unit <b | kb | mb | gb | tb>] [-a | --all] [-n | --newline] [-p | --precision <precision>] [-v | --version] [directory]"
-  exit
+#
+# bytes
+# Sum the number of bytes in a directory listing
+# Written by HP Dietz | h.p.dietz@gmail.com
+#
+
+readonly VERSION=1.4.0
+readonly NUMBER_REGEX="^[0-9]+$"
+readonly ARGS="$@"
+#TOTAL_BYTES=0
+#UNIT=bytes
+#DIR=.
+#LS_OPTS=l
+#PRINT_NEWLINE=true
+#PRECISION=3
+#UNIT_FACTOR=1
+
+usage() {
+  echo "Usage: bytes [-u | --unit <b | kb | mb | gb | tb>] [-a | --all] [-n | --newline] [-p | --precision <precision>] [-v | --version] [directory]" >&2
 }
 
-function printVersionAndExit {
+printVersionAndExit() {
   echo "bytes v$VERSION"
   exit
 }
@@ -61,28 +67,136 @@ function printDirSize {
   fi
 }
 
-while [ "$#" -gt 0 ]; do
-  case "$1" in
-    -u|--unit) setUnit "$2"; shift 2;;
-    -n|--newline) PRINT_NEWLINE=false; shift 1;;
-    -a|--all) LS_OPTS+="a"; shift 1;;
-    -p|--precision) setPrecision "$2"; shift 2;;
-    -v|--version) printVersionAndExit;;
-    -*) echo "Unknown option: $1" >&2; printUsageAndExit;;
-    *) setDir $1; shift 1;;
+getUnitFactor() {
+  local unit=$1
+  local outVar=$2
+  case "$unit" in
+    b)
+      eval $outVar=1
+      ;;
+    kb)
+      eval $outVar=1024
+      ;;
+    mb)
+      let f=1024**2
+      eval $outVar=$f
+      ;;
+    gb)
+      let f=1024**3
+      eval $outVar=$f
+      ;;
+    tb)
+      let f=1024**4
+      eval $outVar=$f
+      ;;
+    *)
+      echo "Invalid unit: $unit" >&2;
+      usage
+      exit 1
+      ;;
   esac
-done
+}
 
-for Bytes in $(ls -${LS_OPTS} ${DIR} | grep "^-" | awk '{ print $5 }')
-do
-    let TOTAL_BYTES=$totalBytes+$Bytes
-done
+getPrecision() {
+  local precision=$1
+  local outVar=$2
 
-case "$UNIT" in
-  kbytes) let UNIT_FACTOR=1024;;
-  mbytes) let UNIT_FACTOR=1024**2;;
-  gbytes) let UNIT_FACTOR=1024**3;;
-  tbytes) let UNIT_FACTOR=1024**4;;
-esac
+  if ! [[ $precision =~ "$NUMBER_REGEX" ]]; then
+    echo "Invalid precision: $precision" >&2
+    usage
+    exit 1
+  fi
+  eval $outVar=$precision
+}
 
-printDirSize $TOTAL_BYTES $UNIT_FACTOR
+parseArgs() {
+  local arg
+  for arg 
+  do
+    case "$arg" in
+      # translate --long-options into short options
+      --all)        args="${args}-a " ;;
+      --newline)    args="${args}-n " ;;
+      --precision)  args="${args}-p " ;;
+      --unit)       args="${args}-u " ;;
+      --version)    args="${args}-v " ;;
+      # pass through anything else
+      *)            args="${args} ${arg} " ;;
+    esac
+  done
+
+  eval set -- $args
+
+  local lsOpts=l
+  local newline=true
+  local precision=3
+  local unitFactor=1
+
+  while getopts "anp:u:v" OPTION;
+  do
+    case $OPTION in
+      a) 
+        lsOpts=${lsOpts}a
+        ;;
+      n)
+        printNewline=false
+        ;;
+      p)
+        getPrecision "$OPTARG" precision
+        ;;
+      u)
+        getUnitFactor "$OPTARG" unitFactor
+        ;;
+      v)
+        printVersion
+        exit 0
+        ;;
+      *)
+        echo "Invalid option: -$OPTION" >&2
+        usage
+        exit 1
+        ;;
+    esac
+  done
+
+  readonly LS_OPTS=$lsOpts
+  readonly NEWLINE=$newline
+  readonly PRECISION=$precision
+  readonly UNIT_FACTOR=$unitFactor
+}
+
+main() {
+  parseArgs $ARGS
+  echo "LS_OPTS: ${LS_OPTS}"
+  echo "NEWLINE: ${NEWLINE}"
+  echo "PRECISTION: ${PRECISION}"
+  echo "UNIT_FACTOR: ${UNIT_FACTOR}"
+}
+
+main
+
+#while [ "$#" -gt 0 ]; do
+#  case "$1" in
+#    -u|--unit) setUnit "$2"; shift 2;;
+#    -n|--newline) PRINT_NEWLINE=false; shift 1;;
+#    -a|--all) LS_OPTS+="a"; shift 1;;
+#    -p|--precision) setPrecision "$2"; shift 2;;
+#    -v|--version) printVersionAndExit;;
+#    -*) echo "Unknown option: $1" >&2; printUsageAndExit;;
+#    *) setDir $1; shift 1;;
+#  esac
+#done
+#
+#for Bytes in $(ls -${LS_OPTS} ${DIR} | grep "^-" | awk '{ print $5 }')
+#do
+#    let TOTAL_BYTES=$totalBytes+$Bytes
+#done
+#
+#case "$UNIT" in
+#  kbytes) let UNIT_FACTOR=1024;;
+#  mbytes) let UNIT_FACTOR=1024**2;;
+#  gbytes) let UNIT_FACTOR=1024**3;;
+#  tbytes) let UNIT_FACTOR=1024**4;;
+#esac
+#
+#printDirSize $TOTAL_BYTES $UNIT_FACTOR
